env:
  es6: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier

plugins:
  - "@typescript-eslint"
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  project:
    - "./tsconfig.json"

rules:
  import/order:
    - error
    - alphabetize:
        order: asc
